config/routes.rb
Adventeur::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  namespace :api do
    namespace :v1 do
      resources :registrations, :only => :create
      resources :checkin, :only => :create
    end
  end
  devise_for :users
  resources :users, :only => :show
  resources :adventures
  resources :checkpoints
  match '/api/v1/search/nearest', :to => "api/v1/search#nearest"
  match '/api/v1/search/intersect', :to => "api/v1/search#intersect"
  match '/app' => redirect("https://play.google.com/store/apps/details?id=co.aventeur.android" ), :as => :app 
end

app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base
  belongs_to :venue # :as => :locatable 
  belongs_to :adventure
  has_many :checkins
  
  reverse_geocoded_by :latitude, :longitude
  scope :start, where(:position => 1)
  acts_as_list :scope => :adventure
 # acts_as_mappable :through => :venue
  
end

app/controllers/checkpoints_controller.rb
class CheckpointsController < ApplicationController
  # GET /checkpoints
  # GET /checkpoints.json
  def index
    @checkpoints = Checkpoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkpoints }
    end
  end

  # GET /checkpoints/1
  # GET /checkpoints/1.json
  def show
    @checkpoint = Checkpoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkpoint }
    end
  end

  # GET /checkpoints/new
  # GET /checkpoints/new.json
  def new
    @checkpoint = Checkpoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @checkpoint }
    end
  end

  # GET /checkpoints/1/edit
  def edit
    @checkpoint = Checkpoint.find(params[:id])
  end

  # POST /checkpoints
  # POST /checkpoints.json
  def create
    adventure = @adventure
    @checkpoint = adventure.checkpoints.new(params[:checkpoint])

    respond_to do |format|
      if @checkpoint.save
        format.html { redirect_to @checkpoint, notice: 'Checkpoint was successfully created.' }
        format.json { render json: @checkpoint, status: :created, location: @checkpoint }
      else
        format.html { render action: "new" }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkpoints/1
  # PUT /checkpoints/1.json
  def update
    @checkpoint = Checkpoint.find(params[:id])

    respond_to do |format|
      if @checkpoint.update_attributes(params[:checkpoint])
        format.html { redirect_to @checkpoint, notice: 'Checkpoint was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkpoint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkpoints/1
  # DELETE /checkpoints/1.json
  def destroy
    @checkpoint = Checkpoint.find(params[:id])
    @checkpoint.destroy

    respond_to do |format|
      format.html { redirect_to checkpoints_url }
      format.json { head :ok }
    end
  end
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/views/checkpoints/_form.html.haml
= form_for @checkpoint do |f|
  -if @checkpoint.errors.any?
    #error_explanation
      %h2= "#{pluralize(@checkpoint.errors.count, "error")} prohibited this checkpoint from being saved:"
      %ul
        - @checkpoint.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tout
    = f.text_field :tout
  .field
    = f.label :venue_id
    = f.number_field :venue_id
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/checkpoints/edit.html.haml
%h1 Editing checkpoint

= render 'form'

= link_to 'Show', @checkpoint
\|
= link_to 'Back', checkpoints_path

app/views/checkpoints/index.html.haml
%h1 Listing checkpoints

%table
  %tr
    %th Tout
    %th Venue
    %th Description
    %th
    %th
    %th

  - @checkpoints.each do |checkpoint|
    %tr
      %td= checkpoint.tout
      %td= checkpoint.venue_id
      %td= checkpoint.description
      %td= link_to 'Show', checkpoint
      %td= link_to 'Edit', edit_checkpoint_path(checkpoint)
      %td= link_to 'Destroy', checkpoint, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Checkpoint', new_checkpoint_path

app/views/checkpoints/new.html.haml
%h1 New checkpoint

= render 'form'

= link_to 'Back', checkpoints_path

app/views/checkpoints/show.html.haml
%p#notice= notice

%p
  %b Tout:
  = @checkpoint.tout
%p
  %b Venue:
  = @checkpoint.venue_id
%p
  %b Description:
  = @checkpoint.description

= link_to 'Edit', edit_checkpoint_path(@checkpoint)
\|
= link_to 'Back', checkpoints_path