config/routes.rb
Adventeur::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  namespace :api do
    namespace :v1 do
      resources :registrations, :only => :create
      resources :checkin, :only => :create
    end
  end
  devise_for :users
  resources :users, :only => :show
  resources :adventures
  resources :checkpoints
  match '/api/v1/search/nearest', :to => "api/v1/search#nearest"
  match '/api/v1/search/intersect', :to => "api/v1/search#intersect"
  match '/app' => redirect("https://play.google.com/store/apps/details?id=co.aventeur.android" ), :as => :app 
end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  has_many :checkpoints, :order => "position"
  belongs_to :user
  has_many :checkins
  
end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  # GET /adventures
  # GET /adventures.json
  def index
    @adventures = Adventure.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @adventures }
    end
  end

  # GET /adventures/1
  # GET /adventures/1.json
  def show
    @adventure = Adventure.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @adventure }
    end
  end

  # GET /adventures/new
  # GET /adventures/new.json
  def new
    @adventure = Adventure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @adventure }
    end
  end

  # GET /adventures/1/edit
  def edit
    @adventure = Adventure.find(params[:id])
  end

  # POST /adventures
  # POST /adventures.json
  def create
    @adventure = current_user.adventures.new(params[:adventure])

    respond_to do |format|
      if @adventure.save
        format.html { redirect_to @adventure, notice: 'Adventure was successfully created.' }
        format.json { render json: @adventure, status: :created, location: @adventure }
      else
        format.html { render action: "new" }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /adventures/1
  # PUT /adventures/1.json
  def update
    @adventure = Adventure.find(params[:id])

    respond_to do |format|
      if @adventure.update_attributes(params[:adventure])
        format.html { redirect_to @adventure, notice: 'Adventure was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @adventure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adventures/1
  # DELETE /adventures/1.json
  def destroy
    @adventure = Adventure.find(params[:id])
    @adventure.destroy

    respond_to do |format|
      format.html { redirect_to adventures_url }
      format.json { head :ok }
    end
  end
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/views/adventures/_form.html.haml
= form_for @adventure do |f|
  -if @adventure.errors.any?
    #error_explanation
      %h2= "#{pluralize(@adventure.errors.count, "error")} prohibited this adventure from being saved:"
      %ul
        - @adventure.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/adventures/edit.html.haml
%h1 Editing adventure

= render 'form'

= link_to 'Show', @adventure
\|
= link_to 'Back', adventures_path

app/views/adventures/index.html.haml
%h1 Listing adventures

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @adventures.each do |adventure|
    %tr
      %td= adventure.name
      %td= adventure.description
      %td= link_to 'Show', adventure
      %td= link_to 'Edit', edit_adventure_path(adventure)
      %td= link_to 'Destroy', adventure, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Adventure', new_adventure_path

app/views/adventures/new.html.haml
%h1 New adventure

= render 'form'

= link_to 'Back', adventures_path

app/views/adventures/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @adventure.name
%p
  %b Description:
  = @adventure.description

.create-a-checkpoint
  = link_to("Create a New Checkpoint", new_checkpoint_path)

.checkpoints
  %table
    %tr
      %th Tout
      %th Venue
      %th Description
      %th
      %th
      %th

    - @adventure.checkpoints.each do |checkpoint|
      %tr
        %td= checkpoint.tout
        %td= checkpoint.venue_id
        %td= checkpoint.description
        %td= link_to 'Show', checkpoint
        %td= link_to 'Edit', edit_checkpoint_path(checkpoint)
        %td= link_to 'Destroy', checkpoint, :confirm => 'Are you sure?', :method => :delete

 
= link_to 'Edit', edit_adventure_path(@adventure)
\|
= link_to 'Back', adventures_path